# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatabasesProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatabasesProject

  target 'DatabasesProjectTests' do
    inherit! :search_paths
pod "SwiftChart"
    # Pods for testing
  end

  target 'DatabasesProjectUITests' do
    inherit! :search_paths
pod "SwiftChart"
    # Pods for testing
  end

end
